services:
  db:
    image: mysql:8.0
    container_name: restaurant_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: restaurant_management
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Ho_Chi_Minh" # ÉP MYSQL CHẠY GIỜ VIỆT NAM
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      # Dòng quan trọng nhất ở đây:
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-time-zone='+07:00' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build: ./backend
    container_name: restaurant_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      TZ: "Asia/Ho_Chi_Minh" # ÉP CONTAINER BACKEND CHẠY GIỜ VIỆT NAM LUÔN CHO CHẮC
      # ĐÃ ĐỔI UTC THÀNH Asia/Ho_Chi_Minh
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Ho_Chi_Minh"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurant_management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123456"
