-- SQL Script to seed categories and menu_items data with VND prices
-- Generated automatically

SET NAMES utf8mb4;

-- Khởi tạo cấu trúc cơ sở dữ liệu nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS `categories` (
  `category_id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) NOT NULL,
  `name_en` varchar(255) NOT NULL,
  `name_vi` varchar(255) NOT NULL,
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `menu_items` (
  `item_id` bigint NOT NULL AUTO_INCREMENT,
  `description_en` text,
  `description_vi` text,
  `discount` double DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `is_available` bit(1) DEFAULT NULL,
  `name_en` varchar(255) NOT NULL,
  `name_vi` varchar(255) NOT NULL,
  `price` decimal(38,2) DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  KEY `FK5bg0vbmql5ggu48n7d5pwgjg3` (`category_id`),
  CONSTRAINT `FK5bg0vbmql5ggu48n7d5pwgjg3` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------------------------------------
-- Tiếp tục các câu lệnh INSERT dữ liệu của bạn ở phía dưới...
-- -------------------------------------------------------------------------

-- Insert Data into `categories` table
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (1, b'1', 'Appetizers', 'Khai Vị');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (2, b'1', 'Soups', 'Súp');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (3, b'1', 'Mains', 'Món Chính');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (4, b'1', 'Pasta & Risotto', 'Mì Ý & Cơm Ý');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (5, b'1', 'Desserts', 'Tráng Miệng');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (6, b'1', 'Beverages', 'Đồ Uống');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (7, b'1', 'Classic Cocktails', 'Cocktail Cổ Điển');
INSERT INTO `categories` (`category_id`, `active`, `name_en`, `name_vi`) VALUES (8, b'1', 'Wine', 'Rượu Vang Chai');

-- Insert Data into `menu_items` table

-- Items for category: Appetizers / Khai Vị
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (1, 'Premium pan-seared foie gras served with a delicate rich sweet reduction.', 'Gan ngỗng áp chảo cao cấp kết hợp cùng sốt giảm vị ngọt thanh tinh tế.', 0, "https://jfoodie.ca/cdn/shop/articles/AdobeStock_1016949499_520x500_8a452dc8-9c0b-4c19-bfbb-7f5fdfe2a930.jpg?v=1745168488", b'1', 'Pan-Seared Foie Gras', 'Gan ngỗng áp chảo', 450000.00, 1);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (2, 'Thinly sliced raw beef tenderloin topped with capers, parmesan, and olive oil.', 'Thịt thăn bò sống thái lát mỏng kèm nụ bạch tùng, phô mai parmesan và dầu ô liu.', 0, "https://media-cdn2.greatbritishchefs.com/media/ydbp2eea/img69349.whqc_768x512q90.jpg", b'1', 'Beef Carpaccio', 'Bò sống thái lát', 280000.00, 1);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (3, 'Fresh premium French oysters served chilled on ice with classic mignonette sauce.', 'Hàu Pháp tươi ngon ướp lạnh, dùng kèm sốt mignonette cổ điển.', 0, "https://images.squarespace-cdn.com/content/v1/5d8fd95977e732177d07affe/1591234931561-V75UNQ955RU671A5FSG5/9525E1CE-B820-4F0F-A34D-DBFC9286DFD0_1_201_a.jpeg?format=1500w", b'1', 'Fresh Oysters', 'Hàu Pháp tươi', 360000.00, 1);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (4, 'Fresh Hokkaido scallops cured in citrus juices with herbs and chili.', 'Sò điệp Hokkaido tươi tái chanh với các loại thảo mộc và ớt.', 0, "https://thewrightbrothers.co.uk/cdn/shop/articles/Scallop_-Spits-May-2017-2_53458ba0-d637-4443-98da-3eebf7fd237e.jpg?v=1634631297", b'1', 'Scallop Ceviche', 'Gỏi sò điệp Hokkaido', 320000.00, 1);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (5, 'Crisp romaine lettuce, croutons, and parmesan tossed in creamy Caesar dressing.', 'Xà lách romaine giòn, bánh mì nướng và phô mai parmesan quyện sốt Caesar béo ngậy.', 0, "https://images.food52.com/GN7d85qFhxOEJ3d6zctEKZtc3JM=/39f86194-4b50-4872-82e8-a1f43a51edbf--2019-0611_caesar-salad-with-anchovy-croutons_3x2_julia-gartland_026.jpg?w=3840&q=75", b'1', 'Caesar Salad', 'Salad Caesar', 190000.00, 1);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (6, 'Creamy burrata cheese served with fresh tomatoes, basil, and balsamic glaze.', 'Phô mai burrata mềm béo ăn kèm cà chua tươi, húng tây và sốt balsamic.', 0, "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2022/06/08/VB1308-valerie-bertinelli-burrata-caprese-salad-with-garlic-basil-oil.jpg.rend.hgtvcom.616.462.suffix/1654722055588.webp", b'1', 'Burrata Caprese', 'Salad phô mai Burrata', 240000.00, 1);

-- Items for category: Soups / Súp
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (7, 'Traditional French onion soup topped with melted Gruyere cheese toast.', 'Súp hành tây Pháp truyền thống với bánh mì nướng phô mai nướng chảy.', 0, "https://www.floatingkitchen.net/wp-content/uploads/2025/01/French-Onion-Soup-1-735x490.jpg", b'1', 'French Onion Soup', 'Súp hành tây Pháp', 180000.00, 2);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (8, 'Rich, velvety cream soup infused with aromatic premium truffle mushrooms.', 'Súp kem béo ngậy kết hợp hương vị nấm truffle thượng hạng thơm lừng.', 0, "https://www.rawblend.com.au/wp-content/uploads/2019/10/Mushroom-Truffle-Thyme-Soup-666x375-e1571700178824-1.jpg", b'1', 'Truffle Mushroom Soup', 'Súp kem nấm Truffle', 220000.00, 2);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (9, 'Smooth, creamy luxury soup made from rich simmered lobster stock.', 'Súp kem tôm hùm đậm đà, mịn màng nấu từ nước dùng tôm hùm cô đặc.', 0, "https://www.tastingtable.com/img/gallery/rich-and-creamy-lobster-bisque-recipe/l-intro-1688145019.jpg", b'1', 'Lobster Bisque', 'Súp kem tôm hùm', 290000.00, 2);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (10, 'Comforting soup made with ripe tomatoes, fresh basil, and cream.', 'Súp kem cà chua ấm áp nấu cùng húng tây tươi thanh mát.', 0, "https://lh5.googleusercontent.com/proxy/S1lcA3KTkKlX9lpeBYJY3BK8QMnCry7aDQA82MvCUtMmmp1DM3zWPlTljYwCqGQQFegLSStJ4ZQfyKi1VrYLe2CxOU6MZl33xksSyB2T", b'1', 'Tomato Basil Soup', 'Súp cà chua húng tây', 150000.00, 2);

-- Items for category: Mains / Món Chính
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (11, 'Premium Wagyu beef tenderloin topped with foie gras and rich Rossini sauce.', 'Thăn bò Wagyu thượng hạng kết hợp gan ngỗng và sốt Rossini đậm đà.', 0, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmOAIioYT4759wkZmxpNgXwdwKz0FnrSp6pg&s", b'1', 'Wagyu Beef Rossini', 'Thăn bò Wagyu sốt gan ngỗng', 1450000.00, 3);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (12, 'Tender, succulent grilled lamb chops seasoned with garlic and fresh herbs.', 'Sườn cừu nướng mềm mọng nước, tẩm ướp tỏi và thảo mộc thơm nồng.', 0, "https://thejoyfilledkitchen.com/wp-content/uploads/2020/07/DSC_0075-2.jpg", b'1', 'Grilled Lamb Chops', 'Sườn cừu nướng', 680000.00, 3);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (13, 'Perfectly pan-seared salmon fillet served with a light citrus herb sauce.', 'Cá hồi áp chảo chín tới hoàn hảo, dùng kèm sốt chanh thảo mộc thanh nhẹ.', 0, "https://media.bluediamond.com/uploads/2023/10/23144402/14_Pan-Seared-Salmon-with-Lemon-Cream-Sauce_Almond-Oat-Milk-Photography_P_23-tkc-0087-scaled.jpg", b'1', 'Pan-Seared Salmon', 'Cá hồi áp chảo', 480000.00, 3);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (14, 'Classic French slow-cooked duck leg with crispy skin and tender meat.', 'Đùi vịt nấu chậm kiểu Pháp truyền thống với da giòn và thịt mềm.', 0, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC7Pt-18r1Viqz5o-9YDapfwMerOPum50QwA&s", b'1', 'Classic Duck Confit', 'Đùi vịt nấu chậm', 420000.00, 3);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (15, 'Melt-in-your-mouth slow-cooked beef ribs in a rich red wine reduction.', 'Sườn bò hầm mềm tan trong miệng với sốt vang đỏ cô đặc đậm đà.', 0, "https://i.shgcdn.com/0fdc6793-98e8-4e39-aa59-2a66de2183d9/-/format/auto/-/preview/3000x3000/-/quality/best/", b'1', 'Slow-Cooked Beef Ribs', 'Sườn bò hầm sốt vang', 550000.00, 3);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (16, 'Pan-roasted sea bass with a crisp skin, served over seasonal vegetables.', 'Cá chẽm áp chảo da giòn rụm, ăn kèm rau củ theo mùa.', 0, "https://realfood.tesco.com/media/images/RFO-1400X919PX-Sea-Bass-eaca4b18-9232-49ff-867d-9eb0532adb05-0-1400x919.jpg", b'1', 'Pan-Roasted Sea Bass', 'Cá chẽm áp chảo', 460000.00, 3);

-- Items for category: Pasta & Risotto / Mì Ý & Cơm Ý
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (17, 'Creamy Italian Arborio rice cooked with fragrant black truffle and parmesan.', 'Cơm Ý Arborio nấu sánh mịn với nấm truffle đen thơm lừng và phô mai.', 0, "https://img.taste.com.au/NuRMZXud/w720-h480-cfill-q80/taste/2016/11/scallop-risotto-with-truffle-oil-53214-1.jpeg", b'1', 'Truffle Risotto', 'Cơm Ý nấm Truffle', 380000.00, 4);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (18, 'Linguine pasta tossed with fresh juicy lobster meat in savory tomato sauce.', 'Mì Ý sợi dẹt xào cùng thịt tôm hùm tươi mọng trong sốt cà chua đậm đà.', 0, "https://bittmanproject.com/wp-content/uploads/Lobster-With-Pasta-and-Mint-articleLarge.jpg", b'1', 'Lobster Linguine', 'Mì Ý tôm hùm', 520000.00, 4);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (19, 'Classic Italian pasta served with a rich, slow-simmered beef bolognese sauce.', 'Mì Ý truyền thống dùng kèm sốt thịt bò băm hầm kỹ đậm vị.', 0, "https://img.taste.com.au/ZfBKx8SH/taste/2016/11/beef-and-olive-spaghetti-bolognese-109377-1.jpeg", b'1', 'Beef Bolognese', 'Mì Ý sốt bò băm', 260000.00, 4);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (20, 'Fettuccine pasta with mixed fresh seafood in a light white wine sauce.', 'Mì Ý sợi lớn nấu cùng hải sản thập cẩm sốt vang trắng thanh nhẹ.', 0, "https://perfectlyprovence.co/wp-content/uploads/2023/10/sablefish-in-lemon-cream-over-lavender-fettucine-500x500.jpg", b'1', 'Seafood Fettuccine', 'Mì Ý hải sản sốt vang trắng', 340000.00, 4);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (21, 'Handmade ravioli stuffed with creamy ricotta and spinach in butter sauce.', 'Bánh gối Ý làm thủ công nhân phô mai ricotta và chân vịt sốt bơ.', 0, "https://img.delicious.com.au/az3iTcWh/del/2024/01/ravioli-di-spinaci-e-ricotta-spinach-and-ricotta-ravioli-206064-1.jpg", b'1', 'Ricotta Ravioli', 'Bánh gối Ý phô mai Ricotta', 290000.00, 4);

-- Items for category: Desserts / Tráng Miệng
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (22, 'Rich custard base topped with a texturally contrasting layer of hardened caramelized sugar.', 'Bánh kem custard béo ngậy với lớp đường khò giòn tan bên trên.', 0, "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/2af5146b9eb248e3779a2257c8a15405/Derivates/8320daaa84e57508997471c53529a3a830e9463a.jpg", b'1', 'Crème Brûlée', 'Kem cháy Pháp', 140000.00, 5);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (23, 'Warm chocolate cake with a delightfully rich, liquid chocolate center.', 'Bánh sô-cô-la nướng ấm nóng với nhân sô-cô-la tan chảy đậm đà.', 0, "https://www.foodnetwork.com/content/dam/images/food/fullset/2014/2/19/1/WU0701H_Molten-Chocolate-Cakes_s4x3.jpg", b'1', 'Chocolate Lava', 'Bánh sô-cô-la tan chảy', 160000.00, 5);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (24, 'Classic Italian dessert with coffee-soaked ladyfingers, mascarpone cream, and cocoa.', 'Bánh tráng miệng Ý với bánh sâm panh thấm cà phê, kem mascarpone và ca cao.', 0, "https://www.carluccios.com/cdn/shop/articles/Tiramisu_1d9de3f3-1f3d-40c4-bcab-b1c669a7616d.jpg?v=1752744640", b'1', 'Classic Tiramisu', 'Bánh Tiramisu', 150000.00, 5);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (25, 'Upside-down caramelized apple tart baked with pastry and served warm.', 'Bánh tart táo lật ngược caramel nướng chín tới, dùng khi còn ấm.', 0, "https://rathfinnyestate.com/wp-content/uploads/2020/10/Apple-Tart-Tatin.jpg", b'1', 'Apple Tart Tatin', 'Bánh tart táo kiểu Pháp', 160000.00, 5);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (26, 'A curated selection of artisanal cheeses served with honey and nuts.', 'Khay phô mai tuyển chọn dùng kèm mật ong và các loại hạt.', 0, "https://file.hstatic.net/200000692767/file/cheese-platter__13_.jpg", b'1', 'Cheese Platter', 'Khay phô mai tổng hợp', 350000.00, 5);

-- Items for category: Beverages / Đồ Uống
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (27, 'Premium choice of still or sparkling bottled mineral water.', 'Lựa chọn nước khoáng thiên nhiên có ga hoặc không ga đóng chai cao cấp.', 0, "https://dbcashandcarry.co.za/cdn/shop/products/simg_3208.jpg?v=1653390623", b'1', 'Still / Sparkling Water', 'Nước khoáng / Nước có ga (Acqua Panna / San Pellegrino)', 90000.00, 6);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (28, 'Freshly squeezed ripe oranges full of natural vitamin C and sweetness.', 'Nước cam tươi ép nguyên chất từ những quả cam mọng nước giàu vitamin C.', 0, "https://www.sliceofsugar.com/wp-content/uploads/2026/01/Refreshing-Orange-Juice.webp", b'1', 'Fresh Orange Juice', 'Nước cam ép tươi', 110000.00, 6);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (29, 'Refreshing blended beverage made with assorted sweet and tart wild berries.', 'Sinh tố xay nhuyễn mát lạnh từ các loại quả mọng rừng chua ngọt.', 0, "https://bydash.com/cdn/shop/articles/20250916095956-mixed-20berry-20smoothie.png?v=1758316466", b'1', 'Mixed Berry Smoothie', 'Sinh tố dâu rừng tổng hợp', 130000.00, 6);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (30, 'Crisp Italian soda infused with zesty lime juices and fresh mint.', 'Soda Ý sảng khoái kết hợp nước cốt chanh tươi và lá bạc hà thơm mát.', 0, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbCrZ6698MQ1lSrZXl0vZCO0hTt_XEsXQ10g&s", b'1', 'Classic Lime Mint Italian Soda', 'Soda Ý chanh bạc hà', 95000.00, 6);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (31, 'Intense and bold shot of freshly brewed premium espresso coffee.', 'Cà phê espresso đậm đặc, rang xay nguyên chất pha máy nóng hổi.', 0, "https://opendrinks.io/img/butter-coffee.7a020581.jpg", b'1', 'Hot Espresso', 'Cà phê Espresso nóng', 70000.00, 6);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (32, 'Chilled premium espresso combined with smooth fresh milk over ice.', 'Cà phê espresso thượng hạng hòa quyện cùng sữa tươi và đá mát lạnh.', 0, "https://myeverydaytable.com/wp-content/uploads/ICEDLATTE_0_4.jpg", b'1', 'Iced Latte', 'Cà phê Latte đá', 85000.00, 6);

-- Items for category: Classic Cocktails / Cocktail Cổ Điển
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (33, 'Sophisticated mix of premium gin and dry vermouth, garnished with olives.', 'Sự kết hợp tinh tế giữa rượu gin cao cấp và dry vermouth, kèm quả ô liu.', 0, "https://assets.epicurious.com/photos/5defc7d20bb0a80008b63876/1:1/w_2560%2Cc_limit/ClassicMartini_RECIPE_120519_13893.jpg", b'1', 'Classic Martini', 'Cocktail Martini truyền thống (Rượu Gin & Dry Vermouth)', 240000.00, 7);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (34, 'Iconic bitter-sweet cocktail crafted from gin, Campari, and sweet vermouth.', 'Cocktail vị đắng ngọt biểu tượng làm từ rượu gin, Campari và sweet vermouth.', 0, "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/negroni_26971_16x9.jpg", b'1', 'Negroni', 'Cocktail Negroni (Rượu Gin, Campari & Sweet Vermouth)', 260000.00, 7);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (35, 'Timeless blend of rich bourbon whiskey, aromatic bitters, and sugar.', 'Sự pha trộn vượt thời gian của rượu bourbon, post đắng thảo mộc và đường.', 0, "https://www.anchoreyes.com/app/uploads/2022/06/ar-drink-old-fashioned-min.jpg", b'1', 'Old Fashioned', 'Cocktail Old Fashioned (Rượu Bourbon & Post đắng)', 260000.00, 7);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (36, 'Bubbly Italian aperitif blending Aperol, sparkling Prosecco, and splash of soda.', 'Thức uống khai vị sủi tăm kiểu Ý hòa quyện Aperol, Prosecco và soda.', 0, "https://www.thebottleclub.com/cdn/shop/articles/TBC_recipe_image_5_e868e523-5fd8-4610-b111-d25510514cff-307537.jpg?v=1707230717", b'1', 'Aperol Spritz', 'Cocktail Aperol Spritz (Rượu Aperol, Prosecco & Soda)', 220000.00, 7);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (37, 'Refreshing cuban cocktail with white rum, sugar, lime, mint, and soda.', 'Cocktail Cuba sảng khoái kết hợp rượu rum trắng, đường, chanh, bạc hà và soda.', 0, "https://www.huongnghiepaau.com/wp-content/uploads/2018/05/mojito-la-thuc-uong-noi-tieng.jpg", b'1', 'Mojito', 'Cocktail Mojito (Rượu Rum, chanh, bạc hà & Soda)', 190000.00, 7);

-- Items for category: Wine / Rượu Vang Chai
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (38, 'Prestigious French Champagne with crisp, balanced flavors and fine bubbles.', 'Sâm-panh Pháp danh tiếng với hương vị cân bằng, tươi mát và bọt sủi mịn.', 0, "https://kentstreetcellars.com.au/cdn/shop/files/lifestyle-2-moet-chandon-imperial-brut-nv-750ml.jpg?v=1730954393", b'1', 'Moët & Chandon Brut', 'Sâm-panh Pháp Moët & Chandon', 3200000.00, 8);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (39, 'Elegant French red wine from Bordeaux with notes of dark fruits.', 'Vang đỏ Pháp thanh lịch vùng Bordeaux với hương vị trái cây sẫm màu.', 0, "https://bizweb.dktcdn.net/100/299/056/files/ruou-vang-mouton-cadet-bordeaux.jpg?v=1622803817143", b'1', 'Bordeaux Rouge', 'Vang đỏ Pháp vùng Bordeaux', 1400000.00, 8);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (40, 'Classic Tuscan red wine with vibrant acidity and cherry undertones.', 'Vang đỏ Tuscan cổ điển từ Ý với độ chua sống động và hương anh đào.', 0, "https://winecenter.vn/uploads/images/624c028356340a3bf4c4f4b7/Chianti.jpg", b'1', 'Chianti Classico', 'Vang đỏ Ý vùng Chianti', 1650000.00, 8);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (41, 'Refined French Burgundy red wine showcasing delicate red berry flavors.', 'Vang đỏ Pháp tinh tế vùng Burgundy thể hiện hương vị quả mọng đỏ nhẹ nhàng.', 0, "https://worldwine.com.au/cdn/shop/files/vin-636.jpg?v=1709655633&width=1000", b'1', 'Burgundy Pinot Noir', 'Vang đỏ Pháp vùng Burgundy', 2100000.00, 8);
INSERT INTO `menu_items` (`item_id`, `description_en`, `description_vi`, `discount`, `image_url`, `is_available`, `name_en`, `name_vi`, `price`, `category_id`) VALUES (42, 'Bold, full-bodied American Cabernet Sauvignon with rich oak aromas.', 'Vang đỏ Mỹ Cabernet Sauvignon đậm đà, mạnh mẽ với hương sồi phong phú.', 0, "https://robertmondaviwinery.com/cdn/shop/files/ErinScott_RobertMondavi_July2025_2019_NapaValley_CabernetSauvignon_375mL_65972_WB1Web2-1000Kwide-300dpi_c9c84cf0-abd4-4a25-b55f-290bbcead184.jpg?v=1754314049", b'1', 'Napa Valley Cabernet', 'Vang đỏ Mỹ vùng Napa Valley', 2450000.00, 8);