-- SQL Script to seed blogs data with randomized timestamps and extra long content
-- Generated automatically with pure text content (No HTML tags at all)

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `blogs` (
  `blog_id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) NOT NULL DEFAULT b'1',
  `author_name` varchar(100) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `img_url` varchar(500) DEFAULT NULL,
  `title_en` varchar(255) NOT NULL,
  `title_vi` varchar(255) NOT NULL,
  `summary_en` text,
  `summary_vi` text,
  `content_en` longtext NOT NULL,
  `content_vi` longtext NOT NULL,
  PRIMARY KEY (`blog_id`),
  UNIQUE KEY `UK_slug_blogs` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -------------------------------------------------------------------------
-- Tiến hành chèn 7 dữ liệu mẫu siêu dài cho bảng `blogs`
-- -------------------------------------------------------------------------

INSERT INTO `blogs` (
  `blog_id`, `active`, `author_name`, `created_at`, `slug`, `img_url`, 
  `title_en`, `title_vi`, `summary_en`, `summary_vi`, `content_en`, `content_vi`
) VALUES 
-- Bài 1: Gan ngỗng áp chảo (Thời gian ngẫu nhiên: 15/04/2024)
(
  1, b'1', 'Alex Nguyen', '2024-04-15 14:22:18.000000', 'the-art-of-pan-searing-foie-gras', 'https://48bistro.com.vn/wp-content/uploads/2022/09/hinh-anh_2024-09-30_194730165.png',
  'The Fine Art of Pan-Searing Premium Foie Gras',
  'Nghệ Thuật Áp Chảo Gan Ngỗng Thượng Hạng',
  'Discover the culinary secrets behind creating the perfect pan-seared foie gras, balancing a crispy exterior with a rich, melt-in-your-mouth texture.',
  'Khám phá bí quyết ẩm thực đằng sau món gan ngỗng áp chảo hoàn hảo, tạo sự cân bằng giữa lớp vỏ giòn bên ngoài và kết cấu béo ngậy mềm tan bên trong.',
  'Foie gras remains one of the most revered and celebrated delicacies in global high cuisine, historically rooted in French culinary traditions but admired by gourmands everywhere. The process of achieving a flawless pan-sear on a premium piece of duck or goose liver is a true test of a chef''s instinct, requiring absolute control over thermodynamics, surface tension, and meticulous timing. If the skillet is not hot enough, the liver will simply melt away into a pool of liquid fat, leaving behind a rubbery and unappetizing remnant. Conversely, excessive unmodulated heat will scorch the delicate exterior before the core has a chance to warm through, completely ruining the structural integrity of this expensive ingredient.\n\nTo master the perfect execution, the foundational rule is ensuring that the raw portions of foie gras are kept ice-cold right up until the exact microsecond they make contact with the cooking surface. Chefs typically slice the liver into uniform portions, scored lightly in a crosshatch pattern to facilitate even heat distribution, and then rest them in the coldest part of the refrigerator. The pan itself, preferably a heavy-bottomed cast iron or stainless steel skillet, must be preheated gradually until it is dry and smoking hot. No oil or butter should ever be added to the pan, as the liver contains an incredibly high percentage of natural lipids that will immediately render out upon contact.\n\nWhen the cold foie gras hits the blazing hot metal, the searing process should last for exactly thirty to forty seconds on each side. During this critical window, a beautiful deep amber, caramelized crust forms due to the Maillard reaction, sealing the decadent fats within. As soon as the second side is beautifully browned, the slices must be immediately transferred to a warm plate lined with paper towels to drain excess fat. At our fine dining establishment, we elevate this experience by pairing the rich liver with a handcrafted sweet and tangy seasonal fruit reduction, such as a balsamic-infused fig or raspberry compote, which cuts through the intense creaminess and creates a perfectly balanced symphony of contrasting flavors on the palate.',
  'Gan ngỗng luôn là một trong những món ăn xa xỉ được tôn sùng và ca ngợi nhất trong nền ẩm thực cao cấp toàn cầu, có nguồn gốc lịch sử sâu xa từ truyền thống nấu ăn của người Pháp nhưng lại được những người sành ăn ở khắp mọi nơi ngưỡng mộ. Quy trình để đạt được một lớp áp chảo hoàn hảo trên một miếng gan ngỗng thượng hạng là một bài kiểm tra thực sự đối với bản năng của người đầu bếp, đòi hỏi sự kiểm soát tuyệt đối về nhiệt động lực học, áp suất bề mặt và thời gian chính xác đến từng giây. Nếu chảo không đủ nóng, miếng gan sẽ đơn thuần bị tan chảy thành một vũng mỡ lỏng, để lại một phần vụn dai và không còn chút hấp dẫn nào. Ngược lại, nhiệt độ quá cao không được kiểm soát sẽ làm cháy xém lớp vỏ ngoài tinh tế trước khi phần lõi bên trong kịp ấm lên, phá hủy hoàn toàn cấu trúc của loại nguyên liệu đắt đỏ này.\n\nĐể làm chủ được kỹ thuật thực hiện hoàn hảo này, quy tắc nền tảng là phải đảm bảo các miếng gan ngỗng sống luôn được giữ lạnh sâu cho đến đúng khoảnh khắc chúng tiếp xúc với bề mặt nấu. Các đầu bếp thường cắt gan thành các phần đều nhau, khía nhẹ các đường chéo hình bàn cờ để tạo điều kiện cho nhiệt độ phân bổ đồng đều, sau đó để chúng nghỉ ở phần lạnh nhất của tủ mát. Bản thân chiếc chảo, tốt nhất là chảo gang có đáy dày hoặc chảo thép không gỉ, phải được làm nóng dần cho đến khi khô ráo và bốc khói nhẹ. Tuyệt đối không được thêm bất kỳ loại dầu hoặc bơ nào vào chảo, vì bản thân gan ngỗng đã chứa một tỷ lệ chất béo tự nhiên cực cao và chúng sẽ ngay lập tức tự tiết ra khi gặp nhiệt.\n\nKhi miếng gan ngỗng lạnh chạm vào bề mặt kim loại đang nóng rực, quá trình áp chảo chỉ nên kéo dài chính xác từ ba mươi đến bốn mươi giây cho mỗi mặt. Trong khoảng thời gian ngắn ngủi nhưng cực kỳ quan trọng này, một lớp vỏ caramen màu hổ phách sâu đậm, tuyệt đẹp sẽ hình thành nhờ phản ứng Maillard, giúp khóa chặt lớp mỡ béo ngậy bên trong. Ngay sau khi mặt thứ hai chuyển màu nâu vàng đẹp đẽ, các miếng gan phải được chuyển ngay lập tức sang một chiếc đĩa ấm có lót giấy thấm để loại bỏ lượng mỡ thừa. Tại nhà hàng sang trọng của chúng tôi, chúng tôi nâng tầm trải nghiệm này bằng cách kết hợp miếng gan béo ngậy với một loại sốt giảm vị ngọt thanh từ trái cây theo mùa như mầm vả hoặc mâm xôi om giấm balsamic, giúp phá vỡ độ ngấy đậm đặc và tạo nên một bản giao hương cân bằng hoàn hảo giữa các hương vị tương phản trên vòm họng.'
),

-- Bài 2: Rượu vang và bò Wagyu (Thời gian ngẫu nhiên: 02/09/2024)
(
  2, b'1', 'Andree Minecle', '2024-09-02 19:45:00.000000', 'guide-to-pairing-wine-with-wagyu', 'https://amp.sieuthithitbo.net/uploads/files/2023/06/27/B9-1.jpg',
  'The Ultimate Wine Pairing Guide for Wagyu Beef',
  'Hướng Dẫn Chọn Rượu Vang Kết Hợp Với Bò Wagyu',
  'An expert guide on selecting the perfect bottle of wine to complement the rich, marbled texture of premium Wagyu beef.',
  'Hướng dẫn chuyên sâu từ chuyên gia trong việc lựa chọn chai rượu vang hoàn hảo để tôn lên hương vị của thịt bò Wagyu mọng nước.',
  'When it comes to luxury dining experiences, few combinations are as revered as a beautifully grilled premium Wagyu steak paired with an exceptional bottle of fine wine. Wagyu beef, renowned globally for its unparalleled structural marbling and intensely rich, buttery flavor profile, presents a unique set of challenges and opportunities for a sommelier. The incredibly high concentration of intramuscular monounsaturated fats means that the meat literally melts at room temperature, coating the mouth in a rich, savory layer of lipid richness. Consequently, choosing a generic, light-bodied red wine or an overly delicate white wine will result in the beverage being completely overpowered by the intense profile of the beef.\n\nTo create a truly harmonious culinary pairing, one must understand the chemical interplay between the tannins in the wine and the fats within the meat. Tannins, which are naturally occurring polyphenols found in grape skins and oak barrels, possess a natural astringency that binds to salivary proteins, drying out the mouth. However, when a high-tannin wine meets a rich slice of Wagyu, the tannins bind to the abundant beef fats instead. This process effectively cleanses the palate after every single bite, cutting through the heavy coating of fat and preparing your taste buds for the next luxurious piece of steak. Therefore, bold, full-bodied red wines with robust structures are the undisputed champions for this pairing.\n\nOur sommelier team highly recommends a well-structured Napa Valley Cabernet Sauvignon, an intensely concentrated Australian Shiraz, or a classic, refined Bordeaux blend from the Left Bank. These specific wines possess not only the necessary tannic backbone but also a vibrant acidity and deep dark fruit notes that complement the savory depth of the meat. To guarantee the most optimal tasting experience at our establishment, we always ensure that these heavy, complex red wines are poured into oversized crystal decanters at least forty-five minutes prior to serving. This crucial breathing period allows the tight aromas of blackberry, tobacco, leather, and vanilla to blossom completely, ensuring that every sip matches the exquisite quality of your meal.',
  'Khi nói đến những trải nghiệm ẩm thực xa hoa, hiếm có sự kết hợp nào được tôn sùng hơn một miếng steak Wagyu thượng hạng được nướng đẹp mắt đi kèm với một chai rượu vang hảo hạng xuất sắc. Thịt bò Wagyu, nổi tiếng toàn cầu nhờ các vân mỡ chằng chịt không có đối thủ và hồ sơ hương vị béo ngậy như bơ, đặt ra một loạt thách thức và cơ hội độc đáo cho một chuyên gia thử nếm rượu vang (Sommelier). Sự tập trung cực cao của các chất béo bão hòa đơn trong cơ có nghĩa là thịt bò thực sự tan chảy ngay ở nhiệt độ phòng, bao phủ khoang miệng bằng một lớp mỡ béo ngậy đậm đà. Do đó, việc chọn một loại rượu vang đỏ nhẹ thông thường hoặc một loại vang trắng quá tinh tế sẽ khiến thức uống hoàn toàn bị lấn át bởi hương vị mạnh mẽ của thịt.\n\nĐể tạo ra một sự kết hợp ẩm thực thực sự hài hòa, người ta phải hiểu rõ sự tương tác hóa học giữa chất tannin trong rượu và chất béo trong thịt. Tannin, hợp chất polyphenols tự nhiên tìm thấy trong vỏ nho và thùng gỗ sồi, có vị chát tự nhiên giúp liên kết với các protein trong nước bọt, làm khô vòm miệng. Tuy nhiên, khi một loại rượu có hàm lượng tannin cao gặp một miếng Wagyu béo ngậy, các tannin này sẽ liên kết với lượng mỡ bò dồi dào thay thế. Quá trình này giúp làm sạch vòm họng một cách hiệu quả sau mỗi miếng ăn, phá vỡ lớp mỡ dày và chuẩn bị cho vị giác của bạn sẵn sàng đón nhận miếng steak sang trọng tiếp theo. Vì vậy, các loại vang đỏ đậm đà, mạnh mẽ với cấu trúc vững chắc là những nhà vô địch không thể tranh cãi cho sự kết hợp này.\n\nĐội ngũ sommelier của chúng tôi khuyên bạn nên chọn một chai Cabernet Sauvignon có cấu trúc tốt từ Thung lũng Napa, một chai Shiraz đậm đặc của Úc hoặc một dòng vang phối trộn Bordeaux cổ điển, tinh tế từ vùng Tả ngạn nước Pháp. Những loại rượu cụ thể này không chỉ sở hữu khung tannin cần thiết mà còn có độ axit sống động cùng nốt hương quả mọng đen sâu lắng giúp tôn lên chiều sâu đậm đà của thịt. Để đảm bảo trải nghiệm nếm thử tối ưu nhất tại nhà hàng của chúng tôi, chúng tôi luôn đảm bảo rằng những loại vang đỏ phức tạp này được rót vào các bình chiết thủy tinh (decanter) cỡ lớn ít nhất bốn mươi lăm phút trước khi phục vụ. Khoảng thời gian thở quan trọng này cho phép các hương thơm đang bị bó chặt của quả mâm xôi, thuốc lá, da thuộc và vani được bung tỏa hoàn toàn, đảm bảo từng ngụm rượu đều xứng tầm với chất lượng tinh tế của bữa ăn.'
),

-- Bài 3: Bánh Tiramisu (Thời gian ngẫu nhiên: 24/12/2024)
(
  3, b'1', 'Jack Bobo', '2024-12-24 21:15:33.000000', 'secrets-of-perfect-tiramisu', 'https://bizweb.dktcdn.net/thumb/grande/100/333/744/articles/banh-tiramisu-1-e3ec3080-1b60-4fa7-8910-aa19e31e4d9b.jpg?v=1577694558270',
  'Behind the Scenes: Secrets of a Perfect Italian Tiramisu',
  'Bí Mật Đằng Sau Chiếc Bánh Tiramisu Ý Hoàn Hảo',
  'Learn about the traditional ingredients and techniques that give our Classic Tiramisu its legendary status.',
  'Tìm hiểu về các nguyên liệu truyền thống và kỹ thuật làm nên thương hiệu của chiếc bánh Tiramisu cổ điển tại nhà hàng.',
  'The word Tiramisu literally translates from the Italian language as a poetic phrase meaning "pick me up," a name that perfectly describes the immediate sensory elevation one experiences when tasting a flawless execution of this classic dessert. While it can now be found on thousands of menus globally, creating an authentic version that stays true to its northern Italian roots requires an unwavering commitment to ingredient purity and technical precision. Many modern variations rely heavily on artificial stabilizers, gelatin, or excessive amounts of white sugar to force the cake into shape, but our pastry kitchen rejects these shortcuts in favor of time-tested, labor-intensive artisanal methods.\n\nThe soul of our legendary Tiramisu lies in the meticulous selection of its component parts. We import fresh, velvety Mascarpone directly from the Lombardy region of Italy, ensuring a rich dairy foundation with the perfect percentage of butterfat. For the sponge element, we use authentic, crispy Savoiardi ladyfingers, which possess a specific airy porousness designed to absorb liquid without disintegrating. These delicate biscuits are submersed in a custom blend of freshly brewed premium espresso, enriched with a precise measure of fine dark rum and traditional Marsala wine. The dipping process is a matter of split-second timing; a fraction of a second too long results in a soggy, mushy base, while too brief a dip leaves a hard, dry core.\n\nFurthermore, the cream layer is achieved by whipping fresh egg yolks with sugar over a hot water bath into a smooth, pale ribbon state known as a sabayon, before gently folding it into the softened mascarpone. The egg whites are beaten separately to stiff peaks and integrated with extreme care to maintain maximum aeration, resulting in a cloud-like texture that is structurally stable yet melts instantly on the tongue. The final secret is patience, as a proper Tiramisu must never be served fresh. It requires a mandatory resting period of twenty-four hours in our climate-controlled refrigerators, allowing the coffee, alcohol, and cream to synthesize completely into a unified masterpiece before receiving a final, elegant dusting of bittersweet Dutch cocoa powder right at the moment of service.',
  'Từ Tiramisu dịch nghĩa một cách văn thơ từ tiếng Ý có nghĩa là "hãy kéo tôi lên", một cái tên mô tả hoàn hảo sự thăng hoa giác quan tức thì mà người ta trải nghiệm khi thưởng thức một chiếc bánh tráng miệng cổ điển được thực hiện một cách hoàn hảo. Mặc dù hiện tại món bánh này có thể được tìm thấy trên hàng ngàn thực đơn toàn cầu, nhưng việc tạo ra một phiên bản đích thực giữ đúng cội nguồn miền Bắc nước Ý đòi hỏi một cam kết kiên định về độ tinh khiết của nguyên liệu và sự chính xác trong kỹ thuật. Nhiều biến thể hiện đại phụ thuộc nhiều vào chất làm cứng nhân tạo, gelatin hoặc lượng đường trắng quá mức để ép bánh vào phom dáng, nhưng bếp bánh của chúng tôi từ chối những lối tắt đó để trung thành với các phương pháp thủ công lâu đời, tốn nhiều công sức.\n\nLinh hồn của món Tiramisu huyền thoại của chúng tôi nằm ở việc lựa chọn tỉ mỉ từng thành phần cấu thành. Chúng tôi nhập khẩu phô mai Mascarpone tươi mịn màng trực tiếp từ vùng Lombardy của Ý, đảm bảo một nền tảng sữa béo ngậy với tỷ lệ bơ béo hoàn hảo. Đối với phần cốt bánh, chúng tôi sử dụng bánh sâm panh Savoiardi giòn rụm đích thực, loại bánh sở hữu độ xốp thoáng khí đặc trưng được thiết kế để hấp thụ chất lỏng mà không bị rã ra. Những chiếc bánh quy tinh tế này được nhúng vào một hỗn hợp espresso thượng hạng mới pha theo công thức riêng, tăng cường thêm một lượng rượu rum sẫm màu và rượu vang Marsala truyền thống. Quy trình nhúng bánh được tính toán bằng phần mười giây; chỉ cần quá một chút sẽ dẫn đến phần đế bánh bị sũng nước, nhão nhoét, trong khi nhúng quá nhanh lại để lại phần lõi cứng và khô.\n\nHơn nữa, lớp kem đạt được bằng cách đánh bông lòng đỏ trứng tươi với đường trên một nồi cách thủy nóng cho đến khi chuyển sang trạng thái ruy-băng mịn, nhạt màu gọi là sabayon, trước khi nhẹ nhàng trộn đều vào phô mai mascarpone đã làm mềm. Lòng trắng trứng được đánh riêng đến khi bông cứng và được kết hợp với sự cẩn trọng tột độ để duy trì độ thoáng khí tối đa, tạo ra một kết cấu nhẹ như mây, ổn định về mặt cấu trúc nhưng lại tan chảy ngay lập tức trên đầu lưỡi. Bí mật cuối cùng chính là sự kiên nhẫn, vì một chiếc Tiramisu đúng chuẩn không bao giờ được phục vụ ngay khi vừa làm xong. Nó đòi hỏi một thời gian ủ bắt buộc kéo dài hai mươi tư giờ trong tủ lạnh kiểm soát nhiệt độ của chúng tôi, cho phép cà phê, rượu và kem tổng hợp hoàn toàn thành một kiệt tác thống nhất trước khi được phủ một lớp bột ca cao Hà Lan đắng nhẹ, thanh lịch ngay tại thời điểm phục vụ.'
),

-- Bài 4: Nguồn cung hải sản (Thời gian ngẫu nhiên: 18/05/2025)
(
  4, b'1', 'John Tri Nguyen', '2025-05-18 09:30:12.000000', 'freshest-seafood-sourcing-story', 'https://allseasonsbuffet.com/wp-content/uploads/2022/04/13.png',
  'From Ocean to Table: Sourcing the Freshest Seafood',
  'Từ Đại Dương Đến Bàn Ăn: Hành Trình Sourcing Hải Sản Tươi Ngon',
  'An insider look at how we source our French oysters and Hokkaido scallops to ensure premium quality for our guests.',
  'Cái nhìn chi tiết về cách chúng tôi tuyển chọn hàu Pháp và sò điệp Hokkaido để đảm bảo chất lượng thượng hạng cho thực khách.',
  'The core philosophy that guides our entire culinary operation is that true luxury dining begins long before the ingredients ever reach the kitchen, rooted deeply in the relationships we build with sustainable producers around the world. For an upscale establishment, providing seafood is not merely about writing items on a menu; it is about establishing an unbroken, highly efficient cold-chain logistics network that guarantees oceanic freshness from the moment of harvest directly to the guest''s table. Our patrons demand absolute perfection, and when dealing with delicate marine proteins like raw oysters or wild-caught scallops, there is zero margin for error or delay.\n\nTake, for example, our world-class oyster selection, which are harvested from the cold, nutrient-rich coastal waters of Marennes-Oléron in France. These exceptional bivalves are plucked from their marine beds at dawn, carefully graded, packed in traditional wooden crates with damp seaweed to maintain natural moisture, and immediately placed onto express international flights. Our logistics partners track the temperature of these shipments every minute of the journey, ensuring they remain constantly at a chilly two degrees Celsius. When they arrive at our kitchen doors, our culinarians inspect each oyster individually, checking that the shells are tightly sealed and full of clean brine, ensuring an explosion of pure Atlantic ocean flavor when shucked live for our diners.\n\nSimilarly, our premium jumbo scallops are sourced from the pristine, icy deep seas of Hokkaido, Japan, a region globally revered for producing shellfish with an incredibly sweet flavor and dense, meaty texture. To preserve these pristine characteristics, the scallops are shucked directly on the fishing vessels immediately upon harvest and flash-frozen within minutes using advanced individual quick freezing technology at minus forty degrees. This rapid process prevents the formation of large ice crystals, thereby protecting the delicate cellular walls of the scallop meat. When gently thawed in our kitchen, they retain all of their natural juices and sweetness, allowing us to serve a breathtaking Scallop Ceviche that tastes exactly as if it were prepared right on the Japanese coastline.',
  'Triết lý cốt lõi dẫn dắt toàn bộ hoạt động ẩm thực của chúng tôi là dịch vụ ăn uống cao cấp đích thực phải bắt đầu từ rất lâu trước khi nguyên liệu đến nhà bếp, bắt rễ sâu sắc vào mối quan hệ chúng tôi xây dựng với các nhà sản xuất bền vững trên khắp thế giới. Đối với một nhà hàng sang trọng, việc cung cấp hải sản không đơn thuần là viết các món ăn lên thực đơn; đó là việc thiết lập một mạng lưới hậu cần chuỗi cung ứng lạnh khép kín, hiệu quả cao để đảm bảo độ tươi ngon nguyên bản của đại dương từ thời điểm đánh bắt trực tiếp đến bàn ăn của khách. Thực khách của chúng tôi yêu cầu sự hoàn hảo tuyệt đối, và khi xử lý các loại protein biển tinh tế như hàu sống hoặc sò điệp đánh bắt tự nhiên, hoàn toàn không có chỗ cho sai sót hay sự chậm trễ.\n\nHãy lấy ví dụ về bộ sưu tập hàu đẳng cấp thế giới của chúng tôi, những con hàu được thu hoạch từ vùng nước ven biển lạnh giá, giàu dinh dưỡng của vùng Marennes-Oléron nước Pháp. Những loài động vật thân mềm hai mảnh vỏ đặc biệt này được hái khỏi giường biển vào lúc bình minh, được phân loại cẩn thận, đóng gói trong các thùng gỗ truyền thống với tảo biển ẩm để duy trì độ ẩm tự nhiên, và ngay lập tức được đưa lên các chuyến bay quốc tế tốc hành. Các đối tác hậu cần của chúng tôi theo dõi nhiệt độ của các lô hàng này từng phút trong suốt hành trình, đảm bảo chúng luôn ở mức hai độ C lạnh giá. Khi chúng đến cửa nhà bếp của chúng tôi, các đầu bếp sẽ kiểm tra từng con hàu một, đảm bảo vỏ đóng chặt và chứa đầy nước biển sạch, đảm bảo một sự bùng nổ hương vị đại dương Đại Tây Dương thuần khiết khi tách vỏ sống phục vụ thực khách.\n\nTương tự như vậy, những con sò điệp jumbo thượng hạng của chúng tôi được lấy từ vùng biển sâu băng giá, hoang sơ của Hokkaido, Nhật Bản, một vùng đất được tôn sùng trên toàn cầu vì sản xuất ra loại động vật có vỏ có vị ngọt cực kỳ tự nhiên và kết cấu thịt dày, săn chắc. Để bảo tồn những đặc tính nguyên bản này, sò điệp được tách vỏ trực tiếp trên tàu đánh cá ngay sau khi thu hoạch và cấp đông nhanh trong vòng vài phút bằng công nghệ cấp đông nhanh cá thể tiên tiến ở âm bốn mươi độ C. Quy trình nhanh chóng này ngăn chặn sự hình thành của các tinh thể đá lớn, từ đó bảo vệ các vách tế bào tinh tế của thịt sò điệp. Khi được rã đông nhẹ nhàng trong nhà bếp của chúng tôi, chúng giữ lại toàn bộ nước ngọt tự nhiên, cho phép chúng tôi phục vụ món Gỏi sò điệp Ceviche tuyệt đỉnh với hương vị chính xác như thể nó được chế biến ngay trên bờ biển Nhật Bản.'
),

-- Bài 5: Nấm Truffle đen (Thời gian ngẫu nhiên: 12/11/2025)
(
  5, b'1', 'Kely Mama', '2025-11-12 11:05:45.000000', 'black-truffle-the-black-diamond', 'https://cdn-i.doisongphapluat.com.vn/resize/th/upload/2024/10/20/nam-truffle-kim-cuong-den-trong-thuc-pham-nhung-ai-khong-nen-an-dpsl-1-10130612.jpg',
  'Black Truffle: The Black Diamond of Our Kitchen',
  'Nấm Truffle Đen: Kim Cương Đen Trong Căn Bếp Của Chúng Tôi',
  'Explore the magic of premium black truffles and why they elevate our signature Mushroom Soup and Risotto to the next level.',
  'Khám phá thế giới diệu kỳ của nấm truffle đen thượng hạng và lý do chúng nâng tầm các món súp kem nấm và cơm Ý của chúng tôi.',
  'In the culinary world, certain ingredients hold a mystical power that completely transcends basic sustenance, transforming an ordinary dish into an extraordinary, unforgettable sensory event. Among these rare treasures, the subterranean fungus known as the black truffle, often referred to by European master chefs as the black diamond of the kitchen, is undeniably the most enigmatic. Growing completely underground in a complex symbiotic relationship with the root systems of specific oak and hazelnut trees, these precious fungi cannot be cultivated through industrial farming methods, requiring specialized, highly trained hounds to locate them by scent in the damp autumnal forests of France and Italy.\n\nThe intense allure of the black truffle does not stem from its visual appearance, which is often bumpy, dark, and uneven, but rather from its volatile, incredibly complex aromatic profile. It possesses an earthy, musky scent reminiscent of damp autumn soil, forest floors, wild honey, and a savory funkiness that science has never been able to fully replicate artificially. Because these aromatic compounds are highly sensitive to heat and evaporate rapidly, a chef must treat truffles with extreme reverence. In our kitchen, we utilize authentic fresh winter black truffles, integrating them into our curated dishes using dual culinary techniques designed to extract every single molecule of scent.\n\nFor our signature Truffle Mushroom Soup, we gently infuse finely minced truffle into a rich base of wild porcini, cremini mushrooms, and heavy French cream over low, controlled heat, allowing the natural lipids to absorb and lock in the earthy perfume. Conversely, for our luxurious Wild Mushroom Risotto, we showcase the ingredient in its purest form. The dish is cooked traditionally using rich broth and arborio rice, and then fresh, whole black truffles are shaved directly over the plate right at the guest''s table. The ambient steam rising from the hot, creamy rice acts as a natural vaporizing agent, activating the volatile oils in the thin truffle ribbons instantly and enveloping the entire dining room in a luxurious, intoxicating aroma.',
  'Trong thế giới ẩm thực, một số nguyên liệu sở hữu một sức mạnh thần bí hoàn toàn vượt ra ngoài việc cung cấp dinh dưỡng cơ bản, biến một món ăn bình thường thành một sự kiện giác quan phi thường, không thể nào quên. Trong số những kho báu hiếm có này, loại nấm mọc ngầm dưới lòng đất được gọi là nấm truffle đen, thường được các bậc thầy đầu bếp châu Âu ví như viên kim cương đen của nhà bếp, không thể phủ nhận là thứ bí ẩn nhất. Phát triển hoàn toàn dưới lòng đất trong một mối quan hệ cộng sinh phức tạp với hệ thống rễ của các cây sồi và cây phỉ cụ thể, những loại nấm quý giá này không thể canh tác bằng các phương pháp nông nghiệp công nghiệp, đòi hỏi những chú chó săn chuyên dụng, được huấn luyện bài bản để định vị chúng bằng khứu giác trong những khu rừng mùa thu ẩm ướt của Pháp và Ý.\n\nSức hấp dẫn mạnh mẽ của nấm truffle đen không bắt nguồn từ ngoại hình bên ngoài của nó, thứ thường xù xì, tối màu và không đều, mà là từ hồ sơ hương thơm dễ bay hơi, vô cùng phức tạp. Nó sở hữu một mùi hương trầm ấm, nồng nàn giống như đất ẩm mùa thu, thảm rừng, mật ong hoang dã và một vị đậm đà đặc trưng mà khoa học chưa bao giờ có thể sao chép nhân tạo một cách trọn vẹn. Vì các hợp chất hương thơm này rất nhạy cảm với nhiệt độ và bốc hơi nhanh chóng, người đầu bếp phải đối xử với truffle bằng sự tôn kính tột cùng. Trong nhà bếp của chúng tôi, chúng tôi sử dụng nấm truffle đen mùa đông tươi nguyên bản, tích hợp chúng vào các món ăn được tuyển chọn bằng cách sử dụng kỹ thuật ẩm thực kép được thiết kế để chiết xuất từng phân tử hương thơm.\n\nĐối với món Súp kem nấm Truffle đặc trưng, chúng tôi nhẹ nhàng truyền nấm truffle băm nhỏ vào một nền tảng phong phú gồm nấm linh chi hoang dã, nấm mỡ và kem béo Pháp trên ngọn lửa nhỏ được kiểm soát, cho phép chất béo tự nhiên hấp thụ và khóa chặt hương nước hoa mộc mạc đó. Ngược lại, đối với món Cơm Ý Risotto nấm hoang dã sang trọng, chúng tôi trưng bày nguyên liệu ở dạng tinh khiết nhất. Món ăn được nấu theo cách truyền thống bằng nước dùng đậm đà và gạo arborio, sau đó nấm truffle đen nguyên củ tươi sẽ được bào trực tiếp lên đĩa ngay tại bàn của thực khách. Hơi nước bao quanh bốc lên từ đĩa cơm nóng hổi, béo ngậy đóng vai trò như một chất bốc hơi tự nhiên, kích hoạt các tinh dầu dễ bay hơi trong những lát nấm truffle mỏng ngay lập tức và bao phủ toàn bộ phòng ăn trong một mùi hương sang trọng, say đắm.'
),

-- Bài 6: Nghệ thuật Cocktail cổ điển (Thời gian ngẫu nhiên: 14/01/2026)
(
  6, b'1', 'Roger Keli', '2026-01-14 22:40:19.000000', 'the-renaissance-of-classic-cocktails', 'https://lygiavien.com/cdn/shop/articles/luoc-su-ve-cac-loai-cocktail-co-dien-martini-old-fashioned.webp?v=1728709036',
  'The Renaissance of Classic Cocktails: From Negroni to Martini',
  'Sự Hồi Sinh Của Cocktail Cổ Điển: Từ Negroni Đến Martini',
  'Take a deep dive into the history and precise mixology standards behind our timeless lounge bar drinks.',
  'Đi sâu vào lịch sử và các tiêu chuẩn pha chế chính xác đằng sau những thức uống vượt thời gian tại quầy bar của chúng tôi.',
  'The modern beverage landscape is constantly evolving with flamboyant trends, molecular gastronomy techniques, and overly complex infusions, yet the true mark of an exceptional lounge bar lies in its ability to execute the absolute classics with flawless, unwavering precision. Across the globe, sophisticated drinkers are spearheading a massive cultural renaissance, turning away from sugary, neon-colored concoctions and returning to timeless, historic drinks like the Dry Martini and the Negroni. These iconic recipes have survived for over a century precisely because their internal liquid architecture is perfectly balanced, leaving absolutely no hidden corner for low-quality spirits or improper technical execution to hide.\n\nCrafting a definitive Dry Martini, for instance, is an exercise in extreme minimalism where every single detail is magnified. The process begins with selecting a premium, small-batch London Dry Gin with a vibrant botanical profile of juniper, citrus, and coriander, which is then paired with a whisper of fine French dry vermouth. The critical element that separates an average drink from a legendary one is temperature and water dilution control. Our bartenders stir the mixture with large, crystal-clear, hand-cut ice cubes for exactly thirty seconds. Stirring, rather than shaking, ensures that the liquid chills down to near freezing while maintaining a perfectly silky, glass-like texture without introducing unwanted air bubbles or ice shards that would cloud the presentation.\n\nSimilarly, the Negroni is a beautiful masterclass in bitter-sweet harmony, originating from Italy in the early twentieth century. It relies on a deceptively simple equal-parts ratio of gin, sweet Italian vermouth, and Campari. To elevate this classic at our establishment, we utilize an artisanal vermouth that offers deep botanical notes, and we serve the liquid over a single, dense, ice sphere carved in-house. This massive piece of clear ice possesses a minimal surface area relative to its weight, which means it will chill the cocktail efficiently while melting at an incredibly slow rate, allowing the patron to leisurely sip and appreciate the unfolding layers of bitter orange, herbal complexity, and clean gin crispness without ever watering down the masterful blend.',
  'Bối cảnh đồ uống hiện đại đang không ngừng phát triển với các xu hướng sặc sỡ, kỹ thuật ẩm thực phân tử và các loại dịch truyền quá phức tạp, tuy nhiên dấu ấn thực sự của một quầy bar đẳng cấp lại nằm ở khả năng thực hiện các loại thức uống cổ điển tuyệt đối với sự chính xác hoàn hảo, kiên định. Trên khắp thế giới, những người uống rượu sành điệu đang dẫn đầu một cuộc hồi sinh văn hóa mạnh mẽ, quay lưng lại với những loại đồ uống nhiều đường, màu neon rực rỡ để trở lại với những thức uống lịch sử, vượt thời gian như Dry Martini và Negroni. Những công thức mang tính biểu tượng này đã tồn tại hơn một thế kỷ chính vì cấu trúc chất lỏng bên trong của chúng được cân bằng hoàn hảo, hoàn toàn không để lại một góc khuất nào cho các loại rượu chất lượng thấp hoặc kỹ thuật pha chế kém cỏi lẩn trốn.\n\nVí dụ, việc pha chế một ly Dry Martini chuẩn mực là một bài tập về sự tối giản cực hạn, nơi mọi chi tiết nhỏ đều được phóng đại lên. Quy trình bắt đầu bằng việc lựa chọn một loại rượu London Dry Gin cao cấp, sản xuất thủ công theo mẻ nhỏ với hồ sơ thảo mộc sống động của quả bách xù, cam quýt và ngò rí, sau đó được kết hợp với một chút rượu dry vermouth tinh tế của Pháp. Yếu tố cốt lõi tách biệt một thức uống trung bình với một huyền thoại là kiểm tra nhiệt độ và độ tan của nước. Các bartender của chúng tôi khuấy hỗn hợp với những viên đá khối lớn, trong suốt như pha lê được cắt thủ công trong chính xác ba mươi giây. Việc khuấy, thay vì lắc, đảm bảo chất lỏng lạnh xuống mức gần như đóng băng trong khi vẫn duy trì kết cấu mịn màng như lụa, giống như thủy tinh mà không tạo ra các bọt khí hoặc mảnh đá vụn không mong muốn làm mờ đi vẻ ngoài của ly rượu.\n\nTương tự như vậy, Negroni là một bài học bậc thầy tuyệt đẹp về sự hài hòa giữa vị đắng và vị ngọt, có nguồn gốc từ Ý vào đầu thế kỷ hai mươi. Nó dựa trên một tỷ lệ các phần bằng nhau tưởng chừng như đơn giản gồm gin, vang ngọt vermouth của Ý và Campari. Để nâng tầm món ăn cổ điển này tại nhà hàng của chúng tôi, chúng tôi sử dụng một loại vermouth thủ công mang lại những nốt hương thảo mộc sâu lắng, và chúng tôi phục vụ chất lỏng trên một viên đá hình cầu đặc, duy nhất được đục đẽo tại chỗ. Khối đá trong suốt khổng lồ này sở hữu diện tích bề mặt tối thiểu so với trọng lượng của nó, điều đó có nghĩa là nó sẽ làm lạnh ly cocktail một cách hiệu quả trong khi tan chảy với tốc độ cực kỳ chậm, cho phép thực khách nhâm nhi thong thả và cảm nhận từng tầng hương vị đang mở ra của cam đắng, sự phức tạp của thảo mộc và sự sắc nét sạch sẽ của rượu gin mà không bao giờ làm loãng đi hỗn hợp tài hoa này.'
),

-- Bài 7: Súp tôm hùm Pháp (Thời gian ngẫu nhiên: 03/03/2026)
(
  7, b'1', 'Omomatit', '2026-03-03 15:23:00.000000', 'the-secret-behind-our-lobster-bisque', 'https://i.vietgiaitri.com/2021/3/10/cach-lam-sup-kem-tom-hum-bisque-cua-dau-bep-phap-148-5624613.jpg',
  '24 Hours in the Making: The Secret Behind Our Lobster Bisque',
  '24 Giờ Chế Biến: Bí Mật Đằng Sau Món Súp Kem Tôm Hùm',
  'Discover the labor-intensive culinary process required to yield just a single bowl of our rich, velvety Lobster Bisque.',
  'Khám Phá quy trình chế biến cực kỳ công phu để tạo ra một bát Súp kem tôm hùm đậm đà, mịn màng duy nhất tại nhà hàng.',
  'Within the rigorous and highly disciplined world of traditional French saucier and soup presentation, there is perhaps no dish that demands as much physical stamina, patience, and deep ingredient respect as a classic Lobster Bisque. A genuine bisque is not a simple seafood broth thickened with flour or cornstarch; rather, it is an intensive, multi-stage culinary marathon focused entirely on extracting the absolute maximum depth of flavor from the deep-sea shells of the European lobster. To create just a single, concentrated batch of this velvety soup requires our entire kitchen brigade to dedicate over twenty-four hours of continuous preparation, combining ancestral techniques with premium components.\n\nThe intensive journey begins with the roasting of dozens of clean, heavy lobster shells in massive, high-heat ovens. This dry roasting step is vital because it caramelizes the proteins bound to the chitin armor, releasing an incredibly deep, nutty marine aroma. Once browned, these shells are crushed into small fragments to expose maximum surface area and transferred into a massive copper stockpot. We then introduce a meticulous mirepoix of finely minced sweet onions, carrots, and celery, which are sweated slowly in clarified butter. The mixture is then deglazed by splashing premium French white wine and flamed with an aged VSOP Cognac, creating a dramatic burst of fire that burns off raw alcohol while trapping the complex oak and grape essences within the base.\n\nNext, the pot is filled with pure filtered water, fresh plum tomatoes, tarragon, bay leaves, and black peppercorns, beginning a slow, continuous twelve-hour simmering process. Throughout this overnight period, the liquid gently coaxes out every molecule of gelatin and savory umami from the pulverized shells. The next morning, the solids are pressed through a heavy-duty mechanical sieve to extract every drop of concentrated elixir, which is then reduced further to amplify the intensity. The final, magical step involves enriching this concentrated marine essence with heavy French cream and whipping in cubes of ice-cold cultured butter, resulting in a flawless, silk-like texture with a vibrant coral hue that delivers an explosion of pure ocean luxury with every spoonful.',
  'Trong thế giới khắt khe và kỷ luật cao của nghệ thuật làm sốt và súp truyền thống của Pháp, có lẽ không có món ăn nào đòi hỏi nhiều thể lực, sự kiên nhẫn và sự tôn trọng nguyên liệu sâu sắc như món Súp kem tôm hùm cổ điển (Lobster Bisque). Một món súp bisque chính hiệu không phải là nước dùng hải sản đơn giản được làm đặc bằng bột mỳ hay bột ngô; thay vào đó, nó là một cuộc marathon ẩm thực chuyên sâu, nhiều giai đoạn, hoàn toàn tập trung vào việc chiết xuất chiều sâu hương vị tối đa tuyệt đối từ lớp vỏ của tôm hùm biển sâu châu Âu. Để tạo ra chỉ một mẻ súp tập trung, mịn màng như nhung này đòi hỏi toàn bộ đội ngũ nhà bếp của chúng tôi phải cống hiến hơn hai mươi tư giờ chuẩn bị liên tục, kết hợp các kỹ thuật cổ xưa với các thành phần cao cấp.\n\nHành trình chuyên sâu bắt đầu bằng việc nướng hàng chục lớp vỏ tôm hùm sạch, nặng trong những chiếc lò lớn ở nhiệt độ cao. Bước nướng khô này vô cùng quan trọng vì nó caramen hóa các protein bám trên lớp giáp chitin, giải phóng một mùi hương biển sâu đậm đà, thơm phức như hạt dẻ. Sau khi ngả màu nâu vàng, những chiếc vỏ này được đập vụn thành các mảnh nhỏ để lộ diện tích bề mặt tối đa và chuyển vào một nồi đồng khổng lồ. Sau đó, chúng tôi đưa vào một hỗn hợp mirepoix gồm hành tây ngọt, cà rốt và cần tây băm nhỏ, được xào chậm cho ra nước trong bơ tinh khiết. Hỗn hợp sau đó được khử chảo bằng cách đổ rượu vang trắng cao cấp của Pháp và đốt cháy với rượu Cognac VSOP lâu năm, tạo ra một ngọn lửa bùng lên mạnh mẽ giúp đốt cháy lượng cồn thô trong khi khóa giữ các tinh túy từ gỗ sồi và nho phức tạp bên trong lớp nền.\n\nTiếp theo, nồi được đổ đầy nước lọc tinh khiết, cà chua mận tươi, ngải giấm, lá nguyệt quế và hạt tiêu đen, bắt đầu một quy trình hầm liu riu chậm rãi, liên tục trong mười hai giờ. Trong suốt khoảng thời gian qua đêm này, chất lỏng nhẹ nhàng dỗ dành từng phân tử gelatin và vị ngọt umami đậm đà ra khỏi lớp vỏ đã được nghiền nát. Sáng hôm sau, các phần bã được ép qua một cái rây cơ học hạng nặng để chiết xuất từng giọt tinh chất cô đặc, sau đó tiếp tục được đun giảm chất lỏng để khuếch đại cường độ hương vị. Bước cuối cùng đầy ma thuật bao gồm việc làm phong phú thêm tinh chất biển cô đặc này với kem béo đậm đặc của Pháp và đánh đều với những viên bơ lạt ủ lạnh, tạo ra một kết cấu hoàn hảo, mịn như lụa với màu cam san hô sống động, mang đến một sự bùng nổ của sự xa xỉ đại dương thuần khiết trong từng thìa súp.'
);