# Sửa UTC thành Asia/Ho_Chi_Minh
spring.datasource.url=jdbc:mysql://db:3306/restaurant_management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=celestehousecontact@gmail.com
spring.mail.password=ypjmwgjkninqfuei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
# VNPay Sandbox Config
vnpay.tmnCode=923VUWD3
vnpay.hashSecret=V474P8EY4ZNQPI3ZQOTOYTV5GCP47VKB
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=https://celestehouse.me/api/payment/vnpay-return
# Khi deploy thật: đổi returnUrl thành domain thật


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB